
version: '3.8'
services:
    
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: on-failure
    expose:
      - "2181"
    network_mode: "host"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    container_name: "kafka_container"
    image: bitnami/kafka:latest
    restart: on-failure
    expose:
      - "9092"
    network_mode: "host"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://172.17.0.1:29092,EXTERNAL://172.17.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "172.17.0.1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: 172.17.0.1:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    restart: on-failure
    volumes:
    - ./infrastructure/kowl_config:/etc/kowl/
    ports:
      - "8081:8080"
    #network_mode: "host"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml --kafka.protobuf.git.basic-auth.password="N0k$oftP@ssw0rd2"
    depends_on:
      - kafka
                         